version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '3001:3001'
    environment:
      - OPENAI_API_KEY="${OPENAI_API_KEY}"
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build:
      context: ./question-generator
      dockerfile: Dockerfile.frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  uploads:
